### ISSUE TITLE
Lib is not longer available

### ISSUE THREAD

**Issue by marinaserranomontes** [ernestrc/tylog#2]
Hi Ernest,

Hope you are doing well.

It seems this lib is not longer available in the maven repo. Do you know if it is by the Bintray Sunset? Are you planning to move it to Maven Central or any other repository?

Thanks a lot.

Best,
Marina

**Comment by ernestrc** [comment]
Hi Marina,

Yep this library was hosted on Bintray; I'm sorry to hear that you guys lost access. Did you find a solution? I had not plans on migrating to Maven but I can take a look if you guys are still stuck.

Thanks

**Comment by marinaserranomontes** [comment]
Hi Ernest,

No problem, we have already found a solution using log4j.

Thanks,
Marina
